version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports: [3000:3000]
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports: [3001:3001]
  mongo:
    image: mongo
